# image: # archlinux
#  file: .gitpod.Dockerfile
checkoutLocation: "./repo"
workspaceLocation: "."
# Commands to start on workspace startup
tasks:
  - name: archroot setup
    init: |
      wget http://mir.archlinux.fr/iso/2021.11.01/archlinux-bootstrap-2021.11.01-x86_64.tar.gz
      mv archlinux-bootstrap-2021.11.01-x86_64.tar.gz archimg.tar.gz
      chmod +x ./repo/archroot_setup.sh
    command: bash repo/archroot_setup.sh archimg.tar.gz
 # wget https://raw.githubusercontent.com/etienne1911/arch-custom-live/main/archroot_setup.sh
