# image: # archlinux
#  file: .gitpod.Dockerfile
checkoutLocation: "./repo"
workspaceLocation: "."
# Commands to start on workspace startup
tasks:
  - name: archroot setup
    init: |
      wget http://mir.archlinux.fr/iso/2021.11.01/archlinux-bootstrap-2021.11.01-x86_64.tar.gz
      chmod +x ./repo/archroot_setup.sh
      mkdir /workspace/archroot
      sudo tar xzf archlinux-bootstrap-2021.11.01-x86_64.tar.gz -C /workspace/archroot
      sudo cp /etc/resolv.conf /workspace/archroot/root.x86_64/etc
      echo "Server = http://mir.archlinux.fr/\$repo/os/\$arch" | sudo tee -a /workspace/archroot/root.x86_64/etc/pacman.d/mirrorlist
    command: bash repo/archroot_setup.sh /workspace/archroot
 # wget https://raw.githubusercontent.com/etienne1911/arch-custom-live/main/archroot_setup.sh
