# image: # archlinux
#  file: .gitpod.Dockerfile
checkoutLocation: "./repo"
workspaceLocation: "."
# Commands to start on workspace startup
tasks:
  - name: archroot setup
    init: |
      cd repo
      chmod +x archroot_setup.sh
    command: ./archroot_setup.sh
 # wget https://raw.githubusercontent.com/etienne1911/arch-custom-live/main/archroot_setup.sh
